### ISSUE TITLE
Change GitHub Pages branch recommendation to put docs in same branch as code

### ISSUE THREAD

**Issue by benlk** [10up/Open-Source-Best-Practices#64]
**Is your enhancement related to a problem? Please describe.**
The GitHub Process docs section [Documentation](https://10up.github.io/Open-Source-Best-Practices/github-process/#documentation) reads:

> Depending on the amount of documentation associated with your projects usage instructions, you may find that hosting them as a separate view, such as GitHub Pages or a GitHub wiki, is preferable to markdown files in a `/docs/` subfolder. Note that if you go the GitHub Pages route, that you’ll want to consider a `gh-pages` branch that deploys to your GitHub Pages site.

[Since 2020-07-31, GitHub now supports having GitHub pages build from a maintainer-specified branch](https://github.blog/changelog/2020-07-31-build-and-deploy-github-pages-from-any-branch-beta/), and from a specific folder within the repo. Using this option would allow GH Pages docs to be version-controlled alongside the source code they document, so that the docs and repo

**Describe the solution you'd like**

Something like:

> Depending on the amount of documentation associated with your project's usage instructions, you may find that hosting them in a separate view, such as GitHub Pages or a GitHub wiki, is preferable to markdown files in a `/docs/` subfolder.
>
> If you go the GitHub pages route, you should:
> 
> - create the GitHub Pages root within a folder in the repository such as `/docs/`, and configure GitHub Pages to build from that folder.
> - update the documentation when the corresponding code is updated.
> - configure GitHub Pages to build from the branch of the project that represents the version of the code users will encounter if they are using an up-to-date version of the project. This would be a `release`, `stable`, or `trunk` branch, instead of a `develop` or `gh-pages` branch.
>
> In this way, merging a feature or development branch that contains new/updated code will simultaneously update the documentation to match the new code.

**Describe alternatives you've considered**

Alternatives include our present recommendations for best practices.

**Additional context**

GitHub added the ability to build and deploy GitHub pages from any branch on [July 31, 2020](https://github.blog/changelog/2020-07-31-build-and-deploy-github-pages-from-any-branch-beta/).

This issue follows from https://github.com/10up/Open-Source-Best-Practices/issues/62

**Comment by jeffpaul** [comment]
The suggested update seems good to me.  @helen you 👍🏼 on this update?

**Comment by jeffpaul** [comment]
@benlk want to handle a PR to make these changes?
